### ISSUE TITLE
Wrong website

### ISSUE THREAD

**Issue by Reillyhewitson** [benjisoft/Sourcify.net#2]
The link at the top of the page (https://sourcify.benjisoft.org.uk/) takes you to a website which has information in a foreign language and adverts for an android game. 
![image](https://user-images.githubusercontent.com/31930005/39115056-999296c0-46d8-11e8-8d3d-7b1f1dd52034.png)
![image](https://user-images.githubusercontent.com/31930005/39115084-a8eb7ccc-46d8-11e8-9a15-92c1a3c16bf2.png)
![image](https://user-images.githubusercontent.com/31930005/39115114-bb7206fe-46d8-11e8-8172-74f7601102d1.png)
![image](https://user-images.githubusercontent.com/31930005/39115156-cffd98ea-46d8-11e8-9433-9a96ff0fae1a.png)
![image](https://user-images.githubusercontent.com/31930005/39115180-df252f68-46d8-11e8-8872-c2a40ca75fb3.png)
![image](https://user-images.githubusercontent.com/31930005/39115208-eea00b52-46d8-11e8-889c-03b836bbf2e9.png)

**Comment by benjisoft** [comment]
Thank you for alerting me to this. This is highly concerning as I still own and have control of this domain.

**Comment by benjisoft** [comment]
The issue has been resolved. It was due to a server configuration issue.
